#!/usr/bin/env bash
alias install='pacman -S --noconfirm --needed'

# desktop environment
install i3
install xfce4
install flameshot
install playerctl

# chat
install telegram-desktop
install discord
