#!/usr/bin/env bash
get-content() {
  #
  # Get a function's content.
  #

  type $1 | sed '1,3d;$d'
}


# Verify benchmark file exists.
[[ -f "$1" ]] || { echo "File '$1' not found!" && exit 1; }
source "$1"


# Benchmark functions that begin with 'test_'.
funcs=$(declare -F | awk '/test_/{print $3}')
max=${2:-100}

# Time each function.
for func in $funcs; do
  # Repeat function $max times.
  _test() {
    for ((i=1; i<=$max; i++)); do
      $func > /dev/null 2>&1
    done
  }

  # Result
  echo -ne "\033[1m$func\033[0m"
  time _test
  echo
  unset -f _test
done

