#!/usr/bin/env bash
bookmarks_file="$HOME/.bookmarks"
touch "$bookmarks_file"


usage() {
  echo "./bookmark save mark"
  echo '  save current directory in `mark` key'
  echo
  echo "./bookmark remove mark"
  echo '  remove `mark` key'
  echo
  echo "source ./bookmark mark"
  echo '  save or go to directory saved in `mark` key'
}


get() {
  grep -m 1 -oP "$1: \K(.*?)$" "$bookmarks_file"
}


save() {
  remove "$1"
  echo "$1: $(pwd)" >> "$bookmarks_file"
}


remove() {
  sed -i "/$1:/d" "$bookmarks_file"
}


get_action() {
  case "$1" in
    ls | list)
      cat "$bookmarks_file"
      return
      ;;

    help)
      usage
      return
      ;;
  esac

  if [[ -z $2 ]]; then
    dir="$(get "$1")" && cd "$dir" || echo "Invalid mark: \`$1\`."
    return
  fi

  case "$1" in
    add | save | set)
      save "$2"
      ;;

    remove | delete | del | rm)
      remove "$2"
      ;;

    get)
      echo "$(get "$2")" 
      ;;

    cd)
      cd "$(get "$2")"
      ;;
  esac

}


[[ -z $1 ]] && usage || get_action "$@"
