#!/usr/bin/env bash
case "$1" in
  set)
    wp="${2:-$WALLPAPER_PATH}"
    [[ "$wp" ]] || { echo 'Missing wallpaper path.' && exit 0; }
    [[ -d "$wp" ]] && wp="$(find "$wp" -type f | shuf -n 1)"
    wpg -A "$wp"
    wpg -s "$wp"
    rm "$(dirname "$wp")"/*_wal_sample.png
    ;;

  reload)
    i3-msg reload
    pkill dunst && dunst &
    besterlockscreen -u -e ''
    ;;

  show)
    # Show a list of colors
    colors=(black red green yellow blue magenta cyan white)
    for i in {0..15}; do
      j=$i; (( i > 7 )) && j=$(( i - 8 ))
      echo -e "color$i: \e[38;5;${i}m${colors[$j]}\e[0m"
    done
    ;;

  *)
    echo "usage: $0 [options]"
    echo '  options:'
    echo '    set  -- set wallpaper and generate colorscheme'
    echo '    show -- show a list of colors'
    ;;
esac
