#!/usr/bin/env bash
CMD=''

# get direction to get the pending desktop
case $1 in
  left)  DIRECTION=-1 ;;
  right) DIRECTION=1  ;;
  *) echo "usage: $0 {left,right}" && exit 1 ;;
esac

# get desktop ids
CURRENT_DESKTOP=$(xdotool get_desktop)
PENDING_DESKTOP=$(( CURRENT_DESKTOP + DIRECTION ))
NUM_DESKTOPS=$(xdotool get_num_desktops)

# validate pending desktop
(( PENDING_DESKTOP < 0 || PENDING_DESKTOP >= NUM_DESKTOPS )) && \
  echo 'Invalid desktop.' && \
  exit 1

# get all windows on current desktop
CURRENT_WINDOWS=$(xdotool search --desktop $CURRENT_DESKTOP --class '')
for window in $CURRENT_WINDOWS; do
  CMD+="set_desktop_for_window $window $PENDING_DESKTOP\n"
done

# get all windows on pending desktop
PENDING_WINDOWS=$(xdotool search --desktop $PENDING_DESKTOP --class '')
for window in $PENDING_WINDOWS; do
  CMD+="set_desktop_for_window $window $CURRENT_DESKTOP\n"
done

# switch to workspace
CMD+="set_desktop $PENDING_DESKTOP"

# run window movements
exec xdotool - <<< $(printf "$CMD")
