#!/usr/bin/env bash
#
# Move Window
# github.com/thetarkus
#

# Input validation
(( $# < 2 )) && echo "usage: $0 {left,right,up,down} {number}" && exit 1

# Create position
case $1 in
  left)  POS="-$2 0"  ;;
  right) POS="$2 0" ;;
  up)    POS="0 -$2" ;;
  down)  POS="0 $2"  ;;
esac

# Set window position
exec xdotool getwindowfocus windowmove --sync --relative -- $POS
