#!/usr/bin/env bash

#
# Move processes into new tmux session.
# $@ -> PIDs
#

# ensure reptyr is installed
which reptyr || echo 'reptyr is not installed'

# ensure at least first PID exists
kill -0 "$1" 2&> /dev/null || echo "usage: $0 {pids...}"

# arguments
NEW_SESSION_ARGS="new-session 'reptyr $1;read' \;"
SELECT_LAYOUT_ARGS='select-layout even-vertical'
SPLIT_WINDOW_ARGS=''

# add split window arguments for every other PID
shift  # Shift past first argument
for pid in "$@"; do
  SPLIT_WINDOW_ARGS+="split-window 'reptyr $pid;read' \;"
done

# launch tmux
eval "tmux $NEW_SESSION_ARGS $SPLIT_WINDOW_ARGS $SELECT_LAYOUT_ARGS"
