#!/usr/bin/env bash
source ~/.cache/wal/colors.sh
pkill dunst
dunst \
  -lb "${color0:-#F0F0F0}" \
  -nb "${color0:-#F0F0F0}" \
  -cb "${color0:-#F0F0F0}" \
  -lf "${color15:=#000000}" \
  -nf "${color15:=#000000}" \
  -cf "${color15:=#000000}" \
  -lfr "${color1:=#000000}" \
  -nfr "${color1:=#000000}" \
  -cfr "${color1:=#000000}" &
