#!/usr/bin/env bash
saved_dirs_file="$HOME/.saved-dirs"
[[ -f "$saved_dirs_file" ]] || touch "$saved_dirs_file"


usage () {
  echo 'save-dir save A'
  echo '  save current directory to A value'
  echo
  echo 'save-dir remove A'
  echo '  remove saved directory value'
  echo
  echo 'save-dir A'
  echo '  set current directory to directory saved in A value'
}


get () {
  grep -m 1 -oP "$1: \K(.*?)$" "$saved_dirs_file"
}


save () {
  remove "$1"
  echo "$1: $(pwd)" >> "$saved_dirs_file"
}


remove () {
  sed -i "/$1:/d" "$saved_dirs_file"
}


get_action () {
  case "$1" in
    add | save | set)
      save "$2"
      ;;

    remove | delete | del | rm)
      remove "$2"
      ;;

    ls | list)
      cat "$saved_dirs_file"
      ;;

    get)
      echo "$(get "$2")" 
      ;;

    cd)
      cd "$(get "$2")"
      ;;

    help)
      usage
      ;;

    *)
      dir="$(get "$1")" && [[ -d "$dir" ]] && cd "$dir" || usage
      ;;
  esac
}


[[ -z "$1" ]] && usage || get_action "$@"
