#!/usr/bin/env bash
#
# Launch a scratchpad of any window by classname.
# $1 -> Window classname
# $2 -> Run command
#

get_window_id() {
  #
  # Get window ID(s) of scratchpad.
  #   $1 -> window classname
  #
  xdotool search --classname "$1"
}


is_visible() {
  #
  # Test if window is visible.
  #   $1 -> window classname
  #
  xdotool search --onlyvisible --classname "$1"
}


WINDOW_ID="$(get_window_id "$1")"

# Window is visible
if [[ "$(is_visible "$1")" ]]; then
  xdotool windowminimize "$WINDOW_ID"

# Window is not visible
else
  # Window exists
  if [[ "$WINDOW_ID" ]]; then
    xdotool set_desktop_for_window "$WINDOW_ID" "$(xdotool get_desktop)" && \
      exec xdotool windowactivate "$WINDOW_ID"

  # Window does not exist
  else
    exec $2 & disown
  fi
fi

exit 1
