#!/usr/bin/env bash
launch() {
  #
  # Launch scratchpad.
  #     $1 -> window class name
  #     $2 -> command.
  xdotool search --class $1 && return 1
  $TERMINAL -c $1 -- bash -c "source $HOME/.bashrc;while :;do $2;done" & disown
}

launch math    "$HOME/.scripts/math"
launch scratch "$HOME/.scripts/tmux scratch"
