#!/usr/bin/env bash
[[ "$1" ]] || { echo "Missing first argument." && exit 1; }
case $1 in
  # Kill tmux session
  kill)
    tmux kill-session -t $2
    ;;

  # Kill all tmux sessions
  killall)
    tmux kill-session -a
    ;;

  # List tmux sessions
  l | ls)
    tmux ls
    ;;

  # Run tmux with custom commands
  -*)
    tmux ${@:2}
    ;;

  # Attach or create new session.
  *)
    $HOME/.scripts/save-dir cd "$1"
    tmux a -t $1 || tmux new -s $1
    ;;
esac
exit 0
