#!/usr/bin/env bash
#
# /etc/udev/rules.d/10-trackpoint.rules
# ACTION=="add", SUBSYSTEM=="input", ATTR{name}=="TPPS/2 IBM TrackPoint", ATTR{device/speed}="200", ATTR{device/sensitivity}="250", ATTR{device/press_to_select}="1"
#

device=/sys/devices/platform/i8042/serio1

[[ -d "$device/serio2" ]] && device="$device/serio2" || exit 1
echo ${1:-175} | sudo tee $device/speed
echo ${2:-250} | sudo tee $device/sensitivity
echo ${3:-1} | sudo tee $device/press_to_select

exit 0
