#!/usr/bin/env bash
set_wallpaper() {
  wal -i ~/Pictures/wallpapers
  source "${HOME}/.cache/wal/colors.sh"
}

reload_dunst() {
  pkill dunst && \
  dunst \
    -lb "${color0:-#F0F0F0}" \
    -nb "${color0:-#F0F0F0}" \
    -cb "${color0:-#F0F0F0}" \
    -lf "${color15:=#000000}" \
    -nf "${color15:=#000000}" \
    -cf "${color15:=#000000}" \
    -lfr "${color1:=#000000}" \
    -nfr "${color1:=#000000}" \
    -cfr "${color1:=#000000}" &
}

main() {
  set_wallpaper
  reload_dunst
}

main
